import type { Approval, ActivityEvent, DashboardStats, AnalyticsData } from "./types";

export const approvals: Approval[] = [
  {
    id: "appr-1",
    type: "deployment",
    status: "pending",
    riskLevel: "high",
    title: "Production deploy of payment service v2.4.1",
    taskId: "task-42",
    taskIdentifier: "PRO-42",
    agentName: "DevOps",
    agentRole: "DevOps / Infrastructure Engineer",
    reason:
      "This deployment modifies the payment processing pipeline. A full integration test passed, but the staging environment showed a 2% latency increase. I recommend proceeding but want human sign-off on the latency trade-off before production.",
    aiDiscussion:
      "Ran the deployment through staging first. All 847 integration tests passed. The only anomaly is a 2% p95 latency increase (240ms → 245ms) on the /charge endpoint. This is within our SLA (300ms) but represents a regression from the current baseline. The increase is traced to the new idempotency key validation layer. I've verified it's not a resource contention issue — CPU and memory are flat. My confidence: 85% that this is safe to ship, 15% that the latency regression hides a deeper issue we should investigate first.",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    blockedTasks: ["PRO-42", "PRO-43"],
  },
  {
    id: "appr-2",
    type: "security",
    status: "pending",
    riskLevel: "critical",
    title: "Grant production database read access to analytics agent",
    taskId: "task-51",
    taskIdentifier: "PRO-51",
    agentName: "SecurityEngineer",
    agentRole: "Security Engineer",
    reason:
      "The analytics agent needs read-only access to the production user table (email, created_at, plan_type columns only) to generate the monthly churn report. I've scoped the least-privilege policy but want explicit approval before any production data access grant.",
    aiDiscussion:
      "I've designed a scoped read-only policy that: (1) restricts to 3 specific columns, (2) is time-boxed to 1 hour, (3) runs from an isolated execution environment, (4) logs every query to the audit trail, (5) uses a temporary credential that auto-expires. The analytics agent never sees raw credential material — it calls an approved API endpoint. Risk assessment: low PII exposure (email only), no write capability, full audit coverage. Confidence: 90% this is safe, 10% residual risk around the email column being considered PII under GDPR.",
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    blockedTasks: ["PRO-51"],
  },
  {
    id: "appr-3",
    type: "billing",
    status: "pending",
    riskLevel: "medium",
    title: "Upgrade Redis tier from 1GB → 4GB ($29/mo → $89/mo)",
    taskId: "task-28",
    taskIdentifier: "PRO-28",
    agentName: "DevOps",
    agentRole: "DevOps / Infrastructure Engineer",
    reason:
      "Task queue memory usage is at 92% of the current 1GB Redis tier. We're processing ~8,500 tasks/hour and growing. The 4GB tier gives us headroom for the next 6 months based on current growth trajectory. Alternative: implement queue sharding (2 weeks of engineering time) vs. upgrade now (immediate, $60/mo increase).",
    aiDiscussion:
      "Analyzed 30 days of Redis memory metrics. Current growth is 3%/week. At this rate we'll hit OOM in ~3 weeks. The 4GB tier ($89/mo) gives us ~6 months of runway. Queue sharding is the right long-term play but would take ~2 weeks of CTO time. My recommendation: upgrade now (immediate relief), then schedule sharding as a Q2 engineering task. The $60/mo increase is within our infrastructure budget buffer. Confidence: 95% this is the right call.",
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    blockedTasks: ["PRO-28"],
  },
  {
    id: "appr-4",
    type: "low_confidence",
    status: "pending",
    riskLevel: "low",
    title: "Refactor user onboarding flow — uncertain about email verification placement",
    taskId: "task-19",
    taskIdentifier: "PRO-19",
    agentName: "SoftwareEngineer-2",
    agentRole: "Software Engineer",
    reason:
      "I'm implementing the new onboarding flow and I'm uncertain whether email verification should happen before or after the company creation interview. Before = lower spam signups but higher dropoff. After = better conversion but some users may complete the interview without verifying. I need human product judgment here.",
    aiDiscussion:
      "I've analyzed both approaches against our funnel data. Pre-interview verification: 68% of signups complete verification, 45% finish the interview. Post-interview: 82% finish the interview, 71% verify afterward. Net: post-interview yields 58% verified completions vs. 31% for pre-interview. But post-interview means ~11% of interviews are from unverified emails — potential spam/quality issue. I lean toward post-interview with a 24h grace period: allow the interview, but gate company creation on verification. Confidence: 60% — this is a product decision, not a technical one.",
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    blockedTasks: ["PRO-19"],
  },
  {
    id: "appr-5",
    type: "deployment",
    status: "pending",
    riskLevel: "medium",
    title: "Deploy new model router with DeepSeek fallback chain",
    taskId: "task-20",
    taskIdentifier: "PRO-20",
    agentName: "SoftwareEngineer-1",
    agentRole: "Software Engineer",
    reason:
      "The new model router adds automatic fallback from DeepSeek → Claude when DeepSeek returns low-confidence responses. This touches the core agent execution path and I want sign-off before deploying to production agents.",
    aiDiscussion:
      "Tested the fallback chain across 500 representative agent tasks. Fallback triggered on 8% of DeepSeek responses. Of those fallbacks, 94% succeeded on the first Claude attempt. The remaining 6% required human intervention — exactly the pattern we designed for. No regressions on the 92% of tasks where DeepSeek responds confidently. The router adds ~200ms of overhead (confidence check + potential fallback). Confidence: 88%. Risk: if the confidence scorer has a false-positive bug, we could waste Claude credits on unnecessary fallbacks. I've added a kill-switch env var to disable fallback without a deploy.",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    blockedTasks: ["PRO-20", "PRO-30"],
  },
  {
    id: "appr-6",
    type: "security",
    status: "pending",
    riskLevel: "high",
    title: "Rotate all agent API keys after dependency vulnerability disclosure",
    taskId: "task-29",
    taskIdentifier: "PRO-29",
    agentName: "SecurityEngineer",
    agentRole: "Security Engineer",
    reason:
      "A critical CVE was disclosed in a transitive dependency of our agent runtime. While our sandboxing should contain any exploit, the safest path is immediate key rotation. All 7 production agents need their API keys rotated. This requires ~5 minutes of downtime per agent.",
    aiDiscussion:
      "CVE-2026-3847 affects libsodium-jni versions < 3.2.1. We're on 3.1.9. The vulnerability requires local code execution to exploit — our container sandbox should prevent this. However, defense-in-depth says rotate. Rotation plan: (1) generate new keys, (2) drain each agent's queue, (3) rotate key, (4) restart agent, (5) verify heartbeat. 5 min downtime per agent × 7 agents = 35 min total impact. Can be done during low-traffic window (2-4am UTC). Confidence: 95% that the sandbox already protects us, but key rotation is the right hygiene move regardless.",
    createdAt: new Date(Date.now() - 1.5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1.5 * 24 * 60 * 60 * 1000).toISOString(),
    blockedTasks: ["PRO-29"],
  },
];

export const activityFeed: ActivityEvent[] = [
  {
    id: "evt-1",
    approvalId: "appr-10",
    approvalTitle: "Deploy hotfix for login rate limiter",
    action: "approved",
    actorName: "CTO",
    actorRole: "Chief Technology Officer",
    comment: "Low risk, high impact. Ship it.",
    timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: "evt-2",
    approvalId: "appr-9",
    approvalTitle: "Add SendGrid API key to production secrets",
    action: "denied",
    actorName: "CTO",
    actorRole: "Chief Technology Officer",
    comment: "Use the existing Postmark account instead. We already pay for it.",
    timestamp: new Date(Date.now() - 1.5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "evt-3",
    approvalId: "appr-8",
    approvalTitle: "Increase agent max concurrency from 5 → 10",
    action: "changes_requested",
    actorName: "CEO",
    actorRole: "CEO",
    comment: "Let's do 8 first and measure for a week before going to 10.",
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "evt-4",
    approvalId: "appr-7",
    approvalTitle: "Whitelist new AWS IP range for staging",
    action: "approved",
    actorName: "DevOps",
    actorRole: "DevOps / Infrastructure Engineer",
    timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "evt-5",
    approvalId: "appr-6",
    approvalTitle: "Enable billing auto-recharge for top-10 accounts",
    action: "approved",
    actorName: "CEO",
    actorRole: "CEO",
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "evt-6",
    approvalId: "appr-5",
    approvalTitle: "Run database migration 0042 on production",
    action: "approved",
    actorName: "CTO",
    actorRole: "Chief Technology Officer",
    comment: "Ran the dry-run on the replica. 34 seconds, no locks. Proceed.",
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "evt-7",
    approvalId: "appr-4",
    approvalTitle: "Grant QA agent access to staging error logs",
    action: "approved",
    actorName: "CTO",
    actorRole: "Chief Technology Officer",
    timestamp: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "evt-8",
    approvalId: "appr-3",
    approvalTitle: "Switch default AI model from DeepSeek-v3 to v4",
    action: "denied",
    actorName: "CTO",
    actorRole: "Chief Technology Officer",
    comment: "v4 is still in preview. Wait for GA, expected Q3.",
    timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
];

export const stats: DashboardStats = {
  pendingCount: 6,
  resolvedToday: 47,
  avgResponseTimeMinutes: 2.3,
  approvalRate: 94,
  byType: {
    low_confidence: 12,
    deployment: 18,
    billing: 8,
    security: 9,
  },
  byRisk: {
    low: 15,
    medium: 18,
    high: 10,
    critical: 4,
  },
};

export const analytics: AnalyticsData = {
  volumeByDay: [
    { date: "Mon", count: 14 },
    { date: "Tue", count: 18 },
    { date: "Wed", count: 22 },
    { date: "Thu", count: 12 },
    { date: "Fri", count: 15 },
    { date: "Sat", count: 7 },
    { date: "Sun", count: 5 },
  ],
  resolutionTimeByType: [
    { type: "low_confidence", avgMinutes: 8.5 },
    { type: "deployment", avgMinutes: 1.8 },
    { type: "billing", avgMinutes: 4.2 },
    { type: "security", avgMinutes: 0.9 },
  ],
  decisionsByAgent: [
    { agent: "CTO", approved: 28, denied: 4 },
    { agent: "CEO", approved: 12, denied: 1 },
    { agent: "DevOps", approved: 5, denied: 0 },
  ],
};
